---
name: beis_nails_art
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  back_button_interceptor: ^8.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  stylish_bottom_bar: ^1.1.0
  supabase_flutter: ^2.8.2
  table_calendar: ^3.2.0
  flutter_svg: ^2.0.17
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  freezed: ^3.0.2
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
